import "server-only";

import { embedQuery } from "./embeddings";
import type { MediaType } from "./media";
import type { Asset, SearchResponse } from "./types";
// The index is generated by `npm run build:index` into src/data/asset-index.json
// and bundled into the build via this static import, so it is guaranteed to be
// present at runtime regardless of the host's build/runtime filesystem split.
// A committed placeholder (empty `assets`) keeps this import resolvable before
// the first build.
import indexData from "@/data/asset-index.json";

// Shape persisted by scripts/build-index.mjs
interface IndexRecord {
  id: string;
  title: string;
  url: string;
  description: string;
  mediaType: MediaType;
  driveLink: string;
  createdTime: string;
  v: number[];
}

interface IndexFile {
  model: string;
  dimensions: number;
  builtAt: string;
  assets: IndexRecord[];
}

interface LoadedRecord {
  asset: Asset;
  createdTime: string;
  /** Unit-normalised embedding for fast cosine via dot product. */
  vec: Float32Array;
}

interface LoadedIndex {
  records: LoadedRecord[];
  /** Records ordered newest-first, for empty queries. */
  byRecency: LoadedRecord[];
}

// Cap on how many ranked hits we expose per query (the long tail is noise).
const MAX_HITS = 300;

let loaded: LoadedIndex | null | undefined;

function normalise(v: number[]): Float32Array {
  let sum = 0;
  for (const x of v) sum += x * x;
  const inv = sum > 0 ? 1 / Math.sqrt(sum) : 0;
  const out = new Float32Array(v.length);
  for (let i = 0; i < v.length; i++) out[i] = v[i] * inv;
  return out;
}

function loadIndex(): LoadedIndex | null {
  if (loaded !== undefined) return loaded;

  const file = indexData as unknown as IndexFile;
  if (!file?.assets?.length) {
    loaded = null;
    return null;
  }

  const records: LoadedRecord[] = file.assets.map((r) => ({
    asset: {
      id: r.id,
      title: r.title,
      url: r.url,
      description: r.description,
      mediaType: r.mediaType,
      driveLink: r.driveLink,
    },
    createdTime: r.createdTime,
    vec: normalise(r.v),
  }));

  const byRecency = [...records].sort((a, b) =>
    b.createdTime.localeCompare(a.createdTime),
  );

  loaded = { records, byRecency };
  return loaded;
}

/** True if a prebuilt index is bundled. */
export function hasIndex(): boolean {
  return loadIndex() !== null;
}

function dot(a: Float32Array, b: Float32Array): number {
  let s = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) s += a[i] * b[i];
  return s;
}

export async function semanticSearch(
  query: string,
  offset = 0,
  pageSize = 24,
): Promise<SearchResponse> {
  const index = loadIndex();
  if (!index) throw new Error("Search index not loaded");

  let ranked: LoadedRecord[];

  if (!query.trim()) {
    // No query → most recent assets first.
    ranked = index.byRecency;
  } else {
    const qvec = normalise(await embedQuery(query));
    ranked = index.records
      .map((r) => ({ r, score: dot(qvec, r.vec) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, MAX_HITS)
      .map((x) => x.r);
  }

  const page = ranked.slice(offset, offset + pageSize);
  const nextOffset = offset + pageSize;
  return {
    results: page.map((r) => r.asset),
    nextCursor: nextOffset < ranked.length ? String(nextOffset) : null,
  };
}
